defaults:
  - encoder@feature_extractor: ptv3_object
  - flow_model: point_cloud_dit

_target_: rectified_point_flow.modeling.RectifiedPointFlow

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 1e-4
  betas: [0.95, 0.999]
  weight_decay: 1e-6
  eps: 1e-8

lr_scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: True
  milestones: [1000, 1200, 1400, 1600, 1800]
  gamma: 0.5

timestep_sampling: "u_shaped"
inference_sampling_steps: 50
