# Main configuration for Rectified Point Flow training

defaults:
  - model: rectified_point_flow
  - data: joint
  - trainer: default
  - loggers: wandb
  - _self_

# Random seed for reproducibility
seed: 42

# Experiment name
experiment_name: "RPF_base_joint"
log_dir: ./output/${experiment_name}
ckpt_path: ${log_dir}/last.ckpt

# Data root
data_root: "../dataset"

# Load pretraining checkpoint
model:
  feature_extractor_ckpt: ./weights/RPF_base_joint.ckpt
  flow_model_ckpt: ./weights/RPF_base_joint.ckpt
