# Rectified Point Flow demo

defaults:
  - model: rectified_point_flow
  - data: ikea_partnet_everyday_twobytwo_modelnet_tudl
  - trainer: main
  - loggers: wandb
  - visualizer: default
  - _self_
  - override hydra/hydra_logging: disabled

# Disable hydra logging
hydra:
  verbose: false
  output_subdir: null
  run:
    dir: .

# Trainer
trainer:
  devices: 1
  strategy: auto
  
# Data
data_root: ./demo/data
data:
  dataset_names: []  # [] means using all datasets in the data_root
  batch_size: 1
  num_workers: 1

# Log directory
log_dir: ./demo/

# Checkpoint path
ckpt_path: ./weights/RPF_base.ckpt

# Define pretrained checkpoints
model:
  encoder_ckpt: null
  flow_model_ckpt: null
