_target_: rectified_point_flow.visualizer.VisualizationCallback

save_dir: ${log_dir}
center_points: false
scale_to_original_size: false

colormap: default
image_size: 256
point_radius: 0.015
camera_dist: 4.0
camera_elev: 30.0
camera_azim: 150.0
camera_fov: 35.0

# Trajectory GIF settings
save_trajectory: true
trajectory_gif_fps: 30
trajectory_gif_pause_last_frame: 1.0